### ISSUE TITLE
Добавить фильтры отображаемых заказов в /manager

### ISSUE THREAD

**Issue by pinkslot** [sosed/qp#69]
managerController::actionIndex() в случае отправки GET-параметров: 'after', 'before', 'status' будет использовать их в качестве аргументов для фильтров выборки заказов из БД.

**Comment by chernov-s** [comment]
Посылаю запрос /manager?before=2017-07-10&after=2017-07-10. Пусть такой запрос остаётся. На бекенде конвертирую эти даты в секунды `strtotime($get['after'])`, но почему-то запрос не срабатывает, хотя время правильно конвертируется
