### ISSUE TITLE
Horizontal scrolling for backend/gridview

### ISSUE THREAD

**Issue by pinkslot** [sosed/qp#87]
Гриды которые не помещаются по ширине просто не отображаются за пределами экрана.

**Comment by chernov-s** [comment]
@pinkslot А причём тут вертикальный скрол?

**Comment by pinkslot** [comment]
@sosed а как ты предлагаешь эту проблему решить? Ну вообще на твоё усмотрение конечно. Ой точно не вертикальный а горизонтальный

**Comment by chernov-s** [comment]
Готово. Добавлена зависимость в композер
